### ISSUE TITLE
Loading chat list fails

### ISSUE THREAD

**Issue by nicodh** [dignifiedquire/dc40#6]
I have 2 fresh created account databases (created with core repl) in ~/.deltachat/
and added chats (also with core repl).

Accounts are listed in dc-next but loading a chat list fails with:
{"level":30,"time":1601713358366,"msg":"selecting account"}
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: failed to load chats: Sqlite Error: QueryReturnedNoRows
Caused by:
    Query returned no rows', backend/src/main.rs:25:48
(on current master)

or in the branch "switch-accounts" with:
Loading chat list for account: "tmp.jhrd7@testrun.org"
{"level":30,"time":1601712707913,"msg":"Could not load chat list: failed to load chats: Sqlite Error: QueryReturnedNoRows\n\nCaused by:\n    Query returned no rows"}

**Comment by okdistribute** [comment]
Also ran into this.

**Comment by nicodh** [comment]
I implemented a workaround in https://github.com/dignifiedquire/dc40/pull/5/commits/7c2fccd5b4718e227add980af6ad9d73c24c6972 but I still don't get why the error occurs in core when we load it in dc-next

**Comment by okdistribute** [comment]
@nicodh awesome thanks for that. Should we make a pull request on this repository so others can get started? Do you have time to do that or want me to?

**Comment by nicodh** [comment]
It's already part of https://github.com/dignifiedquire/dc40/pull/5 - maybe you can review it to speed things up. @dignifiedquire seems pretty busy I guess ;-)

**Comment by dignifiedquire** [comment]
should be fixed
