### ISSUE TITLE
[feature request] Use trunk as bundler

### ISSUE THREAD

**Issue by Septias** [dignifiedquire/dc40#7]
Are there any reasons why we are not using [trunk](https://trunkrs.dev/) to bundle dc40?
It's a bundler especially for rust-wasm and written in pure rust and even though, it's still in its early stages it is working and the Yew's recommended bundler.

The only implications I see atm is that we would have to rewrite the less-CSS to sass/scss, but that isn't too hard I guess.

**Comment by dignifiedquire** [comment]
This is the first time I hear about it, I don't think it was around when I started this work.

**Comment by Septias** [comment]
I got some issues running dc40 on Windows, so I might create a new test-branch with trunk because its setup is really easy.
